descriptor_dimension: 8
inputChannel:
    D: 1
    RGB: 3
    RGBD: 4
    RGBM: 4
    RGBDM: 5
inputMode: "RGBD" # "D" or "RGB" or "RGBD" or "RGBDM" for combination among Depth, RGB, Mask
W: 256
H: 256
Width: 256
Height: 256
image_width: 256
image_height: 256

intrisic_matrix_file: "../ITRIP/camera-intrinsics256.txt"
intrisic_matrix_real_file: "../ITRIP/camera-intrinsics_real.txt"

HalfWidth: 128
HalfHeight: 128
setting: "CODs_GraspNet"
saved_path: "trained_models"
usePretrained: True

sim_folder: "DON_data/sim"
real_folder: "DON_data/real"
n_scene: 5
n_image: 50

training:
  # Optimizer config
  learning_rate: 1.0e-4
  learning_rate_decay: 0.9
  steps_between_learning_rate_decay: 5000 # decay the learning rate after this many steps
  weight_decay: 1.0e-4
  num_iterations: 500 # number of iterations to train for
  # Dataset loader config
  num_workers: 8 # num threads/workers for dataset loading
  compute_test_loss: False
  compute_test_loss_rate: 500 # how often to compute the test loss
  test_loss_num_iterations: 50 # how many samples to use to compute the test loss
  garbage_collect_rate: 1
  batch_size: 1

  # Loss function config
  loss_function: pixelwise_contrastive_loss # not currently used
  # Logging config
  logging_rate: 1000 #1000 # how often to print out
  save_rate: 20000 # how often to save the network
  logging_dir: trained_models # where to store trained models

normalize: False
model: "Resnet" # {3 options: Unet || Resnet || Resnet_orig || PSPNet}


loss_function:
  M_masked: 0.5 # margin for masked non-match descriptor distance
  M_background: 0.5 # margin for background
  M_pixel: 10 # Clamp for pixel distance
  match_loss_weight: 1.0
  non_match_loss_weight: 1.0
  use_l2_pixel_loss_on_masked_non_matches: False
  use_l2_pixel_loss_on_background_non_matches: False
  scale_by_hard_negatives: True
  scale_by_hard_negatives_DIFFERENT_OBJECT: True
  alpha_triplet: 0.1
